name: GitHub Next Visualizer

on:
  release:
    types: [ released ]
  workflow_dispatch:
  
concurrency:
  group: ci-visualizer-${{ github.repository }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [ self-hosted, Linux ]
    defaults:
      run:
        working-directory: ./Irene

    steps:
    # Checkout repository.
    - name: Checkout
      uses: actions/checkout@v3

    # Update diagram.
    - name: Update diagram
      uses: githubocto/repo-visualizer@0.7.1
      with:
        output_file: "visualizer.svg"
        excluded_paths: "config,data"
        commit_message: "[CI] Update repo visualizer diagram"
